In [7]:
import numpy as np
import pandas as pd

In [8]:
np.random.seed(100)

In [9]:
my_data = np.random.randint(0,100,(4,3))
print(my_data)

[[ 8 24 67]
 [87 79 48]
 [10 94 52]
 [98 53 66]]


In [10]:
my_dataframe = pd.DataFrame(my_data)
print(my_dataframe)
print(type(my_dataframe))

    0   1   2
0   8  24  67
1  87  79  48
2  10  94  52
3  98  53  66
<class 'pandas.core.frame.DataFrame'>


In [11]:
my_row_index = ['NY','CA','AZ','TX']
my_col_index = ['David','Yael','Avi']
my_index_df = pd.DataFrame(data = my_data, index = my_row_index, columns = my_col_index)
print(my_index_df)

    David  Yael  Avi
NY      8    24   67
CA     87    79   48
AZ     10    94   52
TX     98    53   66


In [12]:
data = pd.read_csv('csv/example.csv')
print(data)

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15


In [13]:
print(data.columns)
print(data.index)

Index(['a', 'b', 'c', 'd'], dtype='object')
RangeIndex(start=0, stop=4, step=1)


In [14]:
print(data.head(5))
print(data.tail(2))
print(data.info())
print(data.describe())
print(data.describe().transpose())

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
    a   b   c   d
2   8   9  10  11
3  12  13  14  15
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       4 non-null      int64
 1   b       4 non-null      int64
 2   c       4 non-null      int64
 3   d       4 non-null      int64
dtypes: int64(4)
memory usage: 260.0 bytes
None
               a          b          c          d
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000
   count  mean       std  min  25%  50%   75%   

In [15]:
print(data['a'])
print(data[['a','b']])
print(data['a'] + data['b'])
data['calc'] = data['a'] + data['b']
print(data)

0     0
1     4
2     8
3    12
Name: a, dtype: int64
    a   b
0   0   1
1   4   5
2   8   9
3  12  13
0     1
1     9
2    17
3    25
dtype: int64
    a   b   c   d  calc
0   0   1   2   3     1
1   4   5   6   7     9
2   8   9  10  11    17
3  12  13  14  15    25


In [16]:
filtered_data = data.drop(0,axis=0)
print(filtered_data)
data.drop('a',axis=1,inplace=True)
print(data)

    a   b   c   d  calc
1   4   5   6   7     9
2   8   9  10  11    17
3  12  13  14  15    25
    b   c   d  calc
0   1   2   3     1
1   5   6   7     9
2   9  10  11    17
3  13  14  15    25


In [17]:
data[data['calc'].between(4,17,inclusive='both')]

b   c   d  calc
1  5   6   7     9
2  9  10  11    17