In [1]:
import numpy as np
np.random.seed(100)

#Excercise 1
+ Make a random array from 1 to 98
+ Calculate:
    - The sum of all elements
    - The sum of each row
    - The sum of each column

In [2]:
random_array = np.random.randint(10,99,(4,3))

In [3]:
print(f"Random array: \n{random_array}")

Random array: 
[[18 34 77]
 [97 89 58]
 [20 62 63]
 [76 24 44]]


In [4]:
sum_all_elements = random_array.sum()
print(f"Sum all elements: \n{sum_all_elements}")

Sum all elements: 
662


In [5]:
sum_each_row = random_array.sum(axis=1)
print(f"Sum each row \n")
for i in range(len(sum_each_row)):
    print(f"Row {i + 1}: sum = {sum_each_row[i]}")

Sum each row 

Row 1: sum = 129
Row 2: sum = 244
Row 3: sum = 145
Row 4: sum = 144


In [6]:
sum_each_col = random_array.sum(axis=0)
print(f"Sum each column: \n")
for i in range (len(sum_each_col)):
    print(f"Column {i + 1}: sum = {sum_each_col[i]}")

Sum each column: 

Column 1: sum = 211
Column 2: sum = 209
Column 3: sum = 242


#Excercise 2
* Create an array with 10 random numbers between 0 to 10
    - Count how many of them are even numbers

In [7]:
random_array_size_10 = np.random.randint(0,10,10)

In [8]:
print(random_array_size_10) 

[1 0 8 4 0 9 6 2 4 1]


In [9]:
count = 0
for element in random_array_size_10:
    if element % 2 == 0:
        count += 1
print(f"There are {count} even numbers in this array")

There are 7 even numbers in this array


#Excercise 3
* Create an array with a sequence of numbers from 0 to 99
    - Reshape the array into a 2 dimentional array 10x10
    - Replace all values above 50 with -1
    - Calculate the sum of all elements
    - Calculate the mean of all elements

In [10]:
seq_arr = np.arange(0,100,1)

In [11]:
print(seq_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [12]:
seq_arr_reshape = seq_arr.reshape(10,10)
print(f"Reshaped array 10 x 10: \n{seq_arr_reshape}")

Reshaped array 10 x 10: 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [13]:
seq_arr_reshape_replaced = seq_arr_reshape.copy()
seq_arr_reshape_replaced[seq_arr_reshape_replaced > 50] = -1
print(f"Replaced values over 50 with -1:\n{seq_arr_reshape_replaced}")

Replaced values over 50 with -1:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


In [14]:
sum_all_elements = seq_arr_reshape_replaced.sum()
print(f"Sum all elements: {sum_all_elements}")

Sum all elements: 1226


In [15]:
avg_all_elements = seq_arr_reshape_replaced.mean()
print(f"The average of all elements is: {avg_all_elements}")

The average of all elements is: 12.26


# Exercise 4
* Create an array with 10 elaments from 0 - 100 with even spaces bewtween them
    - Make a new array that contains the values from this array that are greater than 50 or lower than 20
    - Reshape the array to a possible matrix
 

In [16]:
even_spaced_arr = np.linspace(0,100,10)
print(f"An array with 10 elements and even spaces: \n {even_spaced_arr}")

An array with 10 elements and even spaces: 
 [  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [17]:
filtered_arr = even_spaced_arr[(even_spaced_arr > 50) | (even_spaced_arr < 20)]
print(f"Filtered array with element lower that 20 or higher than 50: \n {filtered_arr}")

Filtered array with element lower that 20 or higher than 50: 
 [  0.          11.11111111  55.55555556  66.66666667  77.77777778
  88.88888889 100.        ]


In [18]:
size = filtered_arr.size
print(size)

7


In [19]:
x_axis = 0
y_axis = 0
for i in range(size):
    if i == 0 or i == 1:
        continue
    if size % i == 0:
        x_axis = i
        y_axis = int(size / i)
if x_axis > 0:
    reshaped_arr = filtered_arr.reshape(x_axis,y_axis)
    print(f"The reshaped array is : \n {reshaped_arr}")
else:
    print("The array cannot be reshaped to a two dimentional array")
        

The array cannot be reshaped to a two dimentional array


# Exercise 5
    - Generate an array with 4x4 elements filled with zeros of type int
    - change the first last and center element to a value between 10 and 100

In [30]:
matrix = np.zeros((4,4), dtype = int)
random_numbers = np.random.randint(10,101,3)
matrix_shape = matrix.shape
matrix[0,0] = random_numbers[0]
matrix[matrix_shape[0] - 1, matrix_shape[1] - 1] = random_numbers[1]
matrix[int(matrix_shape[0]/2 - 1),int(matrix_shape[1]/2 - 1)] = random_numbers[2]
print(f" The updated matrix is: \n {matrix}")

 The updated matrix is: 
 [[63  0  0  0]
 [ 0 27  0  0]
 [ 0  0  0  0]
 [ 0  0  0 84]]
